
// 공격 일반
export const ANOptions = [
  { name : "골밑슛수비저항증가", percent : 	0.03	},
{ name : "골밑덩크수비저항증가", percent : 	0.03	},
{ name : "3점슛노마크성공률상승", percent : 	0.36	},
{ name : "미들슛수비저항증가", percent : 	0.36	},
{ name : "원거리덩크능력치", percent : 	0.36	},
{ name : "유로스탭성공률상승", percent : 	0.58	},
{ name : "사이드홉스텝모션빠르기", percent : 	0.58	},
{ name : "골밑레이업수비저항증가", percent : 	0.67	},
{ name : "원거리레이업수비저항증가", percent : 	0.67	},
{ name : "퀵점퍼발동속도증가", percent : 	0.67	},
{ name : "더블클러치성공률상승", percent : 	0.67	},
{ name : "풋백덩크성공률상승", percent : 	0.91	},
{ name : "3점슛수비저항증가", percent : 	1	},
{ name : "골밑슛능력치", percent : 	1	},
{ name : "골밑덩크능력치", percent : 	1	},
{ name : "원거리덩크성공률상승", percent : 	1	},
{ name : "골밑레이업능력치", percent : 	1	},
{ name : "골밑덩크발동확률상승", percent : 	1.34	},
{ name : "간접공격수돌파속도증가", percent : 	1.34	},
{ name : "드리프트샷성공률상승", percent : 	1.34	},
{ name : "3점슛능력치", percent : 	1.36	},
{ name : "미들슛성공률상승", percent : 	1.36	},
{ name : "3점슛성공률상승", percent : 	2	},
{ name : "원거리레이업능력치", percent : 	2.05	},
{ name : "원거리덩크발동확률상승", percent : 	2.24	},
{ name : "포스트업충돌각도증가", percent : 	2.34	},
{ name : "포스트업속도증가", percent : 	2.34	},
{ name : "백롤턴속도증가", percent : 	2.34	},
{ name : "백드리블모션빠르기", percent : 	2.34	},
{ name : "백워드투스텝속도증가", percent : 	2.34	},
{ name : "슛페이크돌파속도증가", percent : 	2.34	},
{ name : "플로터성공률상승", percent : 	2.34	},
{ name : "훅슛성공률상승", percent : 	2.34	},
{ name : "페이드어웨이성공률상승", percent : 	2.34	},
{ name : "투스텝속도증가", percent : 	2.34	},
{ name : "퀵체인지속도증가", percent : 	2.34	},
{ name : "터닝슛성공률상승", percent : 	2.34	},
{ name : "포스트업돌파충돌저항증가", percent : 	2.34	},
{ name : "포스트업퀵체인지속도증가", percent : 	2.34	},
{ name : "잽스탭속도증가", percent : 	2.34	},
{ name : "앨리웁덩크가능거리증가", percent : 	2.34	},
{ name : "스쿱샷성공률상승", percent : 	2.34	},
{ name : "턴어라운드페이더웨이성공률상승", percent : 	2.34	},
{ name : "골밑덩크성공률상승", percent : 	2.67	},
{ name : "스카이훅슛성공률상승", percent : 	2.67	},
{ name : "팁인슛성공률상승", percent : 	2.67	},
{ name : "매뉴얼레이업가능각도증가", percent : 	2.67	},
{ name : "미들슛능력치", percent : 	3	},
{ name : "원거리레이업가능거리증가	", percent : 	3.6	},
{ name : "돌파속도증가", percent : 	3.67	},
{ name : "롱레인지가능거리증가", percent : 	3.67	},
{ name : "슛터치시슛성공률상승", percent : 	4.67	},
{ name : "어웨이스크린무브이동속도", percent : 	4.67	},

]

// 공격 프셔
export const APOptions = [
  { name : "3점슛수비저항증가", percent : 	1	},
{ name : "미들슛수비저항증가", percent : 	1	},
{ name : "더블클러치성공률상승", percent : 	1	},
{ name : "플로터성공률상승", percent : 	1	},
{ name : "스쿱샷성공률상승", percent : 	1	},
{ name : "팁인슛성공률상승", percent : 	4	},
{ name : "슛터치시성공률상승", percent : 	9	},
{ name : "드리프트샷성공률상승", percent : 	9	},
{ name : "어웨이스크린무브이동속도", percent : 	9	},
{ name : "3점슛성공률상승", percent : 	10.2	},
{ name : "미들슛성공률상승", percent : 	10.2	},
{ name : "3점슛능력치", percent : 	10.8	},
{ name : "미들슛능력치", percent : 	10.8	},
{ name : "원거리레이업가능거리증가", percent : 	11	},
{ name : "돌파속도증가", percent : 	11	},

]

export const ABOptions = [
  { name : "3점슛노마크성공률상승", percent : 	1.84	},
{ name : "원거리덩크성공률상승", percent : 	1.84	},
{ name : "풋백덩크성공률상승", percent : 	1.84	},
{ name : "유로스탭성공률상승", percent : 	1.84	},
{ name : "사이드홉스텝모션빠르기", percent : 	1.84	},
{ name : "미들슛수비저항증가", percent : 	2.02	},
{ name : "3점슛수비저항증가", percent : 	2.02	},
{ name : "원거리레이업가능거리증가", percent : 	2.02	},
{ name : "원거리덩크발동확률상승", percent : 	2.02	},
{ name : "원거리레이업수비저항증가", percent : 	2.02	},
{ name : "골밑덩크수비저항증가", percent : 	2.02	},
{ name : "3점슛성공률상승", percent : 	2.02	},
{ name : "미들슛성공률상승", percent : 	2.02	},
{ name : "퀵점퍼발동속도증가", percent : 	2.02	},
{ name : "더블클러치성공률상승", percent : 	2.02	},
{ name : "앨리웁덩크가능거리증가", percent : 	2.25	},
{ name : "포스트업속도증가", percent : 	2.25	},
{ name : "백워드투스텝속도증가", percent : 	2.25	},
{ name : "포스트업돌파충돌저항증가", percent : 	2.25	},
{ name : "포스트업퀵체인지속도증가", percent : 	2.25	},
{ name : "어웨이스크린무브이동속도", percent : 	2.25	},
{ name : "백롤턴속도증가", percent : 	2.25	},
{ name : "퀵체인지속도증가", percent : 	2.25	},
{ name : "돌파속도증가", percent : 	2.25	},
{ name : "슛페이크돌파속도증가", percent : 	2.25	},
{ name : "투스텝속도증가", percent : 	2.25	},
{ name : "잽스탭속도증가", percent : 	2.25	},
{ name : "간접공격수돌파속도증가", percent : 	2.25	},
{ name : "포스트업충돌각도증가", percent : 	2.25	},
{ name : "골밑슛수비저항증가", percent : 	2.3	},
{ name : "골밑레이업수비저항증가", percent : 	2.3	},
{ name : "플로터성공률상승", percent : 	2.3	},
{ name : "훅슛성공률상승", percent : 	2.3	},
{ name : "스카이훅슛성공률상승", percent : 	2.3	},
{ name : "페이드어웨이성공률상승", percent : 	2.3	},
{ name : "팁인슛성공률상승", percent : 	2.3	},
{ name : "매뉴얼레이업가능각도증가", percent : 	2.3	},
{ name : "슛터치시슛성공률상승", percent : 	2.3	},
{ name : "터닝슛성공률상승", percent : 	2.3	},
{ name : "골밑덩크성공률상승", percent : 	2.3	},
{ name : "골밑덩크발동확률상승", percent : 	2.3	},
{ name : "롱레인지가능거리증가", percent : 	2.3	},
{ name : "턴어라운드페이더웨이성공률상승", percent : 	2.3	},
{ name : "드리프트샷성공률상승", percent : 	2.3	},
{ name : "백드리블모션빠르기", percent : 	2.3	},
{ name : "스쿱샷성공률상승", percent : 	2.3	},

]


// 수비 일반
export const DNOptions =[
  { name :"일반이동충돌각도증가", percent : 	1.15	},
{ name : "이동속도능력치", percent : 	1.35	},
{ name : "몸싸움능력치", percent : 	1.35	},
{ name : "블록능력치", percent : 	1.35	},
{ name : "리바운드능력치", percent : 	1.35	},
{ name : "스틸능력치", percent : 	1.35	},
{ name : "페이스업이동속도증가", percent : 	2.07	},
{ name : "지구력능력치", percent : 	2.35	},
{ name : "지구력최대량증가", percent : 	2.37	},
{ name : "지구력회복량증가", percent : 	2.37	},
{ name : "일반이동충돌저항증가", percent : 	2.37	},
{ name : "인터셉트성공률상승", percent : 	3.7	},
{ name : "오버패스인터셉트성공률상승", percent : 	3.7	},
{ name : "일반이동속도증가", percent : 	3.87	},
{ name : "박스아웃이동속도증가", percent : 	4.7	},
{ name : "다이빙캐치실패확률감소", percent : 	4.7	},
{ name : "다이빙캐치성공률상승", percent : 	4.7	},
{ name : "다이빙캐치가능범위증가", percent : 	4.7	},
{ name : "블록패스성공률상승", percent : 	4.7	},
{ name : "파워리바운드가능거리증가", percent : 	4.7	},
{ name : "박스아웃스윔무브가능각도증가", percent : 	4.7	},
{ name : "디나이인터셉트성공률상승", percent : 	4.7	},
{ name : "파워탭패스가능거리", percent : 	4.7	},
{ name : "스틸속도증가", percent : 	5.2	},
{ name : "패스능력치", percent : 	5.2	},
{ name : "인터셉트가능범위증가", percent : 	5.2	},
{ name : "칩아웃가능범위증가", percent : 	5.2	},
{ name : "매뉴얼블록가능거리증가", percent : 	6.2	},

]

// 수비 프셔
export const DPOptions = [
  { name : "인터셉트성공률상승", percent : 	1	},
{ name : "칩아웃가능범위증가", percent : 	1	},
{ name : "다이빙캐치성공률상승", percent : 	1	},
{ name : "다이빙캐치가능범위증가", percent : 	1	},
{ name : "파워탭패스가능거리", percent : 	1	},
{ name : "지구력능력치", percent : 	4	},
{ name : "파워리바운드가능거리증가", percent : 	7	},
{ name : "이동속도능력치", percent : 	10	},
{ name : "몸싸움능력치", percent : 	10	},
{ name : "스틸속도증가", percent : 	10	},
{ name : "매뉴얼블록가능거리증가", percent : 	10	},
{ name : "블록능력치", percent : 	11	},
{ name : "리바운드능력치", percent : 	11	},
{ name : "스틸능력치", percent : 	11	},
{ name : "일반이동속도증가", percent : 	11	},

]

// 수비 버닝
export const DBOptions =[
  { name : "박스아웃스윔무브가능각도증가", percent : 	4.65	},
{ name : "다이빙캐치실패확률감소", percent : 	4.65	},
{ name : "파워탭패스가능거리", percent : 	4.65	},
{ name : "디나이인터셉트성공률상승", percent : 	4.65	},
{ name : "일반이동충돌각도증가", percent : 	4.7	},
{ name : "박스아웃이동속도증가", percent : 	4.7	},
{ name : "인터셉트가능범위증가", percent : 	4.7	},
{ name : "인터셉트성공률상승", percent : 	4.7	},
{ name : "칩아웃가능범위증가", percent : 	4.7	},
{ name : "다이빙캐치가능범위증가", percent : 	4.7	},
{ name : "파워리바운드가능거리증가", percent : 	4.7	},
{ name : "매뉴얼블록가능거리증가", percent : 	4.7	},
{ name : "스틸속도증가", percent : 	4.7	},
{ name : "다이빙캐치성공률상승", percent : 	4.7	},
{ name : "블록패스성공률상승", percent : 	4.7	},
{ name : "오버패스인터셉트성공률상승", percent : 	4.7	},
{ name : "일반이동출돌저항증가", percent : 	5	},
{ name : "지구력최대량증가", percent : 	5	},
{ name : "지구력회복량증가", percent : 	5	},
{ name : "일반이동속도증가", percent : 	5	},
{ name : "페이스업이동속도증가", percent : 	5	},

]

// 재능 일반
export const TNOptions = [
  { name : "3점슛노마크성공률상승", percent : 	0.18	},
{ name : "포스트업충돌각도증가", percent : 	0.18	},
{ name : "포스트업속도증가", percent : 	0.18	},
{ name : "박스아웃이동속도증가", percent : 	0.18	},
{ name : "페이스업이동속도증가", percent : 	0.18	},
{ name : "퀵점퍼발동속도증가", percent : 	0.18	},
{ name : "슛중패스가능거리증가", percent : 	0.18	},
{ name : "3점슛능력치", percent : 	0.36	},
{ name : "원거리덩크능력치", percent : 	0.37	},
{ name : "원거리덩크성공률상승", percent : 	0.37	},
{ name : "이동속도능력치", percent : 	0.37	},
{ name : "지구력능력치", percent : 	0.37	},
{ name : "인터셉트성공률상승", percent : 	0.37	},
{ name : "파워리바운드가능거리증가", percent : 	0.42	},
{ name : "디나이인터셉트성공률상승", percent : 	0.55	},
{ name : "유로스탭성공률상승", percent : 	0.55	},
{ name : "골밑덩크능력치", percent : 	0.93	},
{ name : "원거리레이업능력치", percent : 	0.93	},
{ name : "훅업패스실패확률감소", percent : 	0.99	},
{ name : "3섬슛수비저항증가", percent : 	1.03	},
{ name : "골밑슛수비저항증가", percent : 	1.03	},
{ name : "골밑덩크성공률상승", percent : 	1.03	},
{ name : "골밑덩크수비저항증가", percent : 	1.03	},
{ name : "골밑덩크발동확률상승", percent : 	1.03	},
{ name : "원거리덩크발동확률상승", percent : 	1.03	},
{ name : "골밑레이업수비저항증가", percent : 	1.03	},
{ name : "원거리레이업수비저항증가", percent : 	1.03	},
{ name : "패스능력치", percent : 	1.03	},
{ name : "지구력최대량증가", percent : 	1.03	},
{ name : "지구력회복량증가", percent : 	1.03	},
{ name : "일반이동충돌각도증가", percent : 	1.03	},
{ name : "일반이동충돌저항증가", percent : 	1.03	},
{ name : "백롤턴속도증가", percent : 	1.03	},
{ name : "백드리블모션빠르기", percent : 	1.03	},
{ name : "백워드투스텝속도증가", percent : 	1.03	},
{ name : "엘리웁패스가능거리증가", percent : 	1.03	},
{ name : "엘리웁패스실패확률감소", percent : 	1.03	},
{ name : "슛페이크돌파속도증가", percent : 	1.03	},
{ name : "더블클러치성공률상승", percent : 	1.03	},
{ name : "플로터성공률상승", percent : 	1.03	},
{ name : "다이빙캐치성공률상승", percent : 	1.03	},
{ name : "다이빙캐치가능범위증가", percent : 	1.03	},
{ name : "다이빙캐치실패확률감소", percent : 	1.03	},
{ name : "훅슛성공률상승", percent : 	1.03	},
{ name : "스카이훅슛성공률상승", percent : 	1.03	},
{ name : "페이드어웨이성공률상승", percent : 	1.03	},
{ name : "투스탭속도증가", percent : 	1.03	},
{ name : "퀵체인지속도증가", percent : 	1.03	},
{ name : "슛터치시슛성공률상승", percent : 	1.03	},
{ name : "터닝슛성공률상승", percent : 	1.03	},
{ name : "블록패스성공률상승", percent : 	1.03	},
{ name : "킬패스속도증가", percent : 	1.03	},
{ name : "킥아웃패스속도증가", percent : 	1.03	},
{ name : "킥아웃패스인터셉트저항증가", percent : 	1.03	},
{ name : "엔트리패스속도증가", percent : 	1.03	},
{ name : "엔트리패스인터셉트저항증가", percent : 	1.03	},
{ name : "포스트업돌파충돌저항증가", percent : 	1.03	},
{ name : "포스트업퀵체인지속도증가", percent : 	1.03	},
{ name : "오버패스인터셉트성공률상승", percent : 	1.03	},
{ name : "박스아웃스윔무브가능각도증가", percent : 	1.03	},
{ name : "잽스탭속도증가", percent : 	1.03	},
{ name : "간접공격수돌파속도증가", percent : 	1.03	},
{ name : "엘리웁덩크성공률상승", percent : 	1.03	},
{ name : "엘리웁덩크가능거리증가", percent : 	1.03	},
{ name : "스쿱샷성공률상승", percent : 	1.03	},
{ name : "드리프트샷성공률상승", percent : 	1.03	},
{ name : "턴어라운드페이더웨이성공률상승", percent : 	1.03	},
{ name : "파워탭패스가능거리", percent : 	1.03	},
{ name : "사이드홉스탭모션빠르기", percent : 	1.03	},
{ name : "미들슛능력치", percent : 	1.23	},
{ name : "미들슛수비저항증가", percent : 	1.23	},
{ name : "골밑레이업능력치", percent : 	1.23	},
{ name : "스틸속도증가", percent : 	1.23	},
{ name : "인터셉트가능범위증가", percent : 	1.23	},
{ name : "스크린충돌범위증가", percent : 	1.23	},
{ name : "스크린충돌각도증가", percent : 	1.23	},
{ name : "칩아웃가능범위증가", percent : 	1.23	},
{ name : "팁인슛성공률상승", percent : 	1.23	},
{ name : "풋백덩크성공률상승", percent : 	1.23	},
{ name : "매뉴얼레이업가능각도증가", percent : 	1.23	},
{ name : "롱레인지가능거리증가", percent : 	1.23	},
{ name : "어웨이스크린무브이동속도", percent : 	1.23	},
{ name : "블록능력치", percent : 	1.37	},
{ name : "3점슛성공률상승", percent : 	2.23	},
{ name : "미들슛성공률상승", percent : 	2.23	},
{ name : "원거리레이업가능거리증가", percent : 	2.23	},
{ name : "몸싸움능력치", percent : 	2.23	},
{ name : "리바운드능력치", percent : 	2.23	},
{ name : "스틸능력치", percent : 	2.23	},
{ name : "일반이동속도증가", percent : 	2.23	},
{ name : "돌파속도증가", percent : 	2.23	},
{ name : "매뉴얼블록가능거리증가", percent : 	2.23	},
{ name : "골밑슛능력치", percent : 	3.23	},
  ];

// 재능 프리미엄
export const TPOptions = [
{ name : "3점슛수비저항증가", percent : 	3	},
{ name : "미들슛수비저항증가", percent : 	3	},
{ name : "이동속도능력치", percent : 	3	},
{ name : "몸싸움능력치", percent : 	3	},
{ name : "스틸속도증가", percent : 	3	},
{ name : "인터셉트성공률상승", percent : 	3	},
{ name : "더블클러치성공률상승", percent : 	3	},
{ name : "플로터성공률상승", percent : 	3	},
{ name : "다이빙캐치성공률상승", percent : 	3	},
{ name : "다이빙캐치가능범위증가", percent : 	3	},
{ name : "팁인슛성공률상승", percent : 	3	},
{ name : "슛터치시슛성공률상승", percent : 	3	},
{ name : "파워리바운드가능거리증가", percent : 	3	},
{ name : "메뉴얼블록가능거리증가", percent : 	3	},
{ name : "스쿱샷성공률상승", percent : 	3	},
{ name : "드리프트샷성공률상승", percent : 	3	},
{ name : "어웨이스크린무브이동속도", percent : 	3	},
{ name : "파워탭패스가능거리", percent : 	3	},
{ name : "3점슛성공률상승", percent : 	3.2	},
{ name : "미들슛성공률상승", percent : 	3.2	},
{ name : "3점슛능력치", percent : 	3.8	},
{ name : "미들슛능력치", percent : 	3.8	},
{ name : "원거리레이업가능거리증가", percent : 	4	},
{ name : "블록능력치", percent : 	4	},
{ name : "리바운드능력치", percent : 	4	},
{ name : "스틸능력치", percent : 	4	},
{ name : "지구력능력치", percent : 	4	},
{ name : "일반이동속도증가", percent : 	4	},
{ name : "돌파속도증가", percent : 	4	},
{ name : "칩아웃가능범위증가", percent : 	4	}


];

//재능 버닝
export const TBOptions = [
  { name : "훅슛성공률상승", percent : 	0.6	},
{ name : "훅업패스실패확률감소", percent : 	0.6	},
{ name : "골밑덩크능력치", percent : 	0.8	},
{ name : "골밑레이업능력치", percent : 	0.8	},
{ name : "골밑슛능력치", percent : 	0.8	},
{ name : "롱레인지가능거리증가", percent : 	0.8	},
{ name : "매뉴얼레이업가능각도증가", percent : 	0.8	},
{ name : "스크린충돌각도증가", percent : 	0.8	},
{ name : "스크린충돌범위증가", percent : 	0.8	},
{ name : "원거리덩크능력치", percent : 	0.8	},
{ name : "원거리덩크성공률상승", percent : 	0.8	},
{ name : "원거리레이업능력치", percent : 	0.8	},
{ name : "인터셉트가능범위증가", percent : 	0.8	},
{ name : "풋백덩크성공률상승", percent : 	0.8	},
{ name : "3점슛노마크성공률상승", percent : 	0.8	},
{ name : "간접공격수돌파속도증가", percent : 	0.8	},
{ name : "골밑덩크발동확률상승", percent : 	0.8	},
{ name : "골밑덩크성공률상승", percent : 	0.8	},
{ name : "골밑덩크수비저항증가", percent : 	0.8	},
{ name : "골밑레이업수비저항증가", percent : 	0.8	},
{ name : "골밑슛수비저항증가", percent : 	0.8	},
{ name : "다이빙캐치실패확률감소", percent : 	0.8	},
{ name : "디나이인터셉트성공률상승", percent : 	0.8	},
{ name : "박스아웃스윔무브가능각도증가", percent : 	0.8	},
{ name : "박스아웃이동속도증가", percent : 	0.8	},
{ name : "백드리블모션빠르기", percent : 	0.8	},
{ name : "백롤턴속도증가", percent : 	0.8	},
{ name : "백워드투스텝속도증가", percent : 	0.8	},
{ name : "블록패스성공률상승", percent : 	0.8	},
{ name : "사이드홉스텝모션빠르기", percent : 	0.8	},
{ name : "슛중패스가능거리증가", percent : 	0.8	},
{ name : "슛페이크돌파속도증가", percent : 	0.8	},
{ name : "스카이훅슛성공률상승", percent : 	0.8	},
{ name : "앨리웁덩크가능거리증가", percent : 	0.8	},
{ name : "앨리웁덩크성공률상승", percent : 	0.8	},
{ name : "앨리웁패스가능거리증가", percent : 	0.8	},
{ name : "앨리웁패스실패확률감소", percent : 	0.8	},
{ name : "엔트리패스속도증가", percent : 	0.8	},
{ name : "엔트리패스인터셉트저항증가", percent : 	0.8	},
{ name : "오버패스인터셉트성공률상승", percent : 	0.8	},
{ name : "원거리덩크발동확률상승", percent : 	0.8	},
{ name : "원거리레이업수비저항증가", percent : 	0.8	},
{ name : "유로스탭성공률상승", percent : 	0.8	},
{ name : "일반이동충돌각도증가", percent : 	0.8	},
{ name : "일반이동충돌저항증가", percent : 	0.8	},
{ name : "잽스탭속도증가", percent : 	0.8	},
{ name : "지구력최대량증가", percent : 	0.8	},
{ name : "지구력회복량증가", percent : 	0.8	},
{ name : "퀵점퍼발동속도증가", percent : 	0.8	},
{ name : "퀵체인지속도증가", percent : 	0.8	},
{ name : "킥아웃패스속도증가", percent : 	0.8	},
{ name : "킥아웃패스인터셉트저항증가", percent : 	0.8	},
{ name : "킬패스속도증가", percent : 	0.8	},
{ name : "터닝슛성공률상승", percent : 	0.8	},
{ name : "턴어라운드페이더웨이성공률상승", percent : 	0.8	},
{ name : "투스텝속도증가", percent : 	0.8	},
{ name : "패스능력치", percent : 	0.8	},
{ name : "페이드어웨이성공률상승", percent : 	0.8	},
{ name : "페이스업이동속도증가", percent : 	0.8	},
{ name : "포스트업돌파충돌저항증가", percent : 	0.8	},
{ name : "포스트업속도증가", percent : 	0.8	},
{ name : "포스트업충돌각도증가", percent : 	0.8	},
{ name : "포스트업퀵체인지속도증가", percent : 	0.8	},
{ name : "미들슛수비저항증가", percent : 	1.2	},
{ name : "스틸속도증가", percent : 	1.2	},
{ name : "어웨이스크린무브이동속도", percent : 	1.2	},
{ name : "이동속도능력치", percent : 	1.2	},
{ name : "인터셉트성공률상승", percent : 	1.2	},
{ name : "팁인슛성공률상승", percent : 	1.2	},
{ name : "3점슛수비저항증가", percent : 	1.2	},
{ name : "다이빙캐치가능범위증가", percent : 	1.2	},
{ name : "다이빙캐치성공률상승", percent : 	1.2	},
{ name : "더블클러치성공률상승", percent : 	1.2	},
{ name : "드리프트샷성공률상승", percent : 	1.2	},
{ name : "슛터치시슛성공률상승", percent : 	1.2	},
{ name : "스쿱샷성공률상승", percent : 	1.2	},
{ name : "파워리바운드가능거리증가", percent : 	1.2	},
{ name : "파워탭패스가능거리", percent : 	1.2	},
{ name : "플로터성공률상승", percent : 	1.2	},
{ name : "3점슛능력치", percent : 	1.4	},
{ name : "미들슛능력치", percent : 	1.4	},
{ name : "지구력능력치", percent : 	1.5	},
{ name : "칩아웃가능범위증가", percent : 	1.5	},
{ name : "3점슛성공률상승", percent : 	2.5	},
{ name : "돌파속도증가", percent : 	2.5	},
{ name : "리바운드능력치", percent : 	2.5	},
{ name : "매뉴얼블록가능거리증가", percent : 	2.5	},
{ name : "몸싸움능력치", percent : 	2.5	},
{ name : "미들슛성공률상승", percent : 	2.5	},
{ name : "블록능력치", percent : 	2.5	},
{ name : "스틸능력치", percent : 	2.5	},
{ name : "원거리레이업가능거리증가", percent : 	2.5	},
{ name : "일반이동속도증가", percent : 	2.5	},

];